import React from 'react'

export default function PeopleSayComponent() {
  return (
    <div className="testimonial-block style-one">
    <div className="container">
      <div className="heading3 text-center">What’s people say’s</div>
      <div className="main-cmt bg-line-dark pl-16 pr-16 pb-60 bora-44 mt-40">
        <div className="row flex-center">
          <div className="col-xl-8 col-lg-9 col-md-10">
            <div className="list-avatar">
              <div className="prev-btn w-40 h-40 flex-center border-white bora-50">
                <i className="ph ph-caret-left fs-20 d-block" />
              </div>
              <div className="avatar">
                <div className="item" data-name={0}>
                  <div className="bg-img">
                    <img src="assets/images/avatar/avatar1.png" alt="" />
                  </div>
                </div>
                <div className="item" data-name={1}>
                  <div className="bg-img">
                    {" "}
                    <img src="assets/images/avatar/avatar4.png" alt="" />
                  </div>
                </div>
                <div className="item" data-name={2}>
                  <div className="bg-img">
                    {" "}
                    <img src="assets/images/avatar/avatar3.png" alt="" />
                  </div>
                </div>
                <div className="item" data-name={3}>
                  <div className="bg-img">
                    {" "}
                    <img src="assets/images/avatar/avatar5.png" alt="" />
                  </div>
                </div>
                <div className="item" data-name={4}>
                  <div className="bg-img">
                    {" "}
                    <img src="assets/images/avatar/avatar6.png" alt="" />
                  </div>
                </div>
                <div className="item" data-name={5}>
                  <div className="bg-img">
                    {" "}
                    <img src="assets/images/avatar/avatar2.png" alt="" />
                  </div>
                </div>
              </div>
              <div className="next-btn w-40 h-40 flex-center border-white bora-50">
                <i className="ph ph-caret-right fs-20 d-block" />
              </div>
            </div>
            <div className="list-comment">
              <div className="cmt-item text-center active" data-name={0}>
                <div className="heading6 fw-500">
                  "Working with this agency has been a game-changer for our
                  business. Their team is knowledgeable, and always goes the extra
                  mile."
                </div>
                <div className="text-button mt-24">Maverick Nguyen</div>
                <div className="caption1 text-placehover mt-4">
                  UI UX Designer, Avitex Inc
                </div>
              </div>
              <div className="cmt-item text-center" data-name={1}>
                <div className="heading6 fw-500">
                  "Thanks to their AI solutions, our customer experience has
                  significantly improved. Personal recommendation fostered
                  stronger relationships."
                </div>
                <div className="text-button mt-24">Christina Smith</div>
                <div className="caption1 text-placehover mt-4">
                  Data Analyst, Microsoft
                </div>
              </div>
              <div className="cmt-item text-center" data-name={2}>
                <div className="heading6 fw-500">
                  "Their AI services have been a reliable partner in our business
                  journey. They've empowered us with data-driven solutions for
                  better results."
                </div>
                <div className="text-button mt-24">David Johnson</div>
                <div className="caption1 text-placehover mt-4">
                  Mobile App Developer, Apple
                </div>
              </div>
              <div className="cmt-item text-center" data-name={3}>
                <div className="heading6 fw-500">
                  "The insight generated by their AI tools have been invaluable.
                  They helped us understand our customer behavior and optimize our
                  AI."
                </div>
                <div className="text-button mt-24">Peter Parker</div>
                <div className="caption1 text-placehover mt-4">
                  Business Analyst, Oracle
                </div>
              </div>
              <div className="cmt-item text-center" data-name={4}>
                <div className="heading6 fw-500">
                  "Smart and Efficient! The AI integration into our workflow has
                  been seamless. It's simplified complex task and improved our
                  resource."
                </div>
                <div className="text-button mt-24">Georgina Rodriguez</div>
                <div className="caption1 text-placehover mt-4">
                  Network Engineer, Amazon
                </div>
              </div>
              <div className="cmt-item text-center" data-name={5}>
                <div className="heading6 fw-500">
                  "Efficiency at Its Best! Remarkable AI Solutions! Our business
                  has witnessed remarkable improvements since integrating their
                  AI."
                </div>
                <div className="text-button mt-24">Rihana Pavard</div>
                <div className="caption1 text-placehover mt-4">
                  Database Administrator, IBM
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  )
}
