
import { Inter } from 'next/font/google'
// import './globals.css'
import '../public/assets/css/animate.min.css'
import 'bootstrap/dist/css/bootstrap.css';
import '../public/assets/css/slick.css'
import '../public/assets/icons/style.css'
import '../public/assets/css/style.css'
import '../public/assets/css/swiper-bundle.min.css'

import Script from 'next/script'
import ScriptComponent from '@/components/ScriptComponent';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  deScription: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Script src="../assets/js/jquery-3.7.0.js" ></Script>
  <Script src="../assets/js/jquery-migrate-3.4.1.js" ></Script>
  <Script src="../assets/js/slick.min.js" ></Script>
  <Script src="../assets/js/scrollreveal.js" ></Script>
  <Script src="../assets/js/swiper-bundle.min.js" ></Script>
  {/* <Script src="../assets/js/bootstrap.bundle.min.js" ></Script> */}
  <Script src="../assets/js/countUp.min.js" ></Script>
  <Script src="../assets/js/waypoints.min.js" ></Script>
  <Script src="../assets/js/phosphor-icons.js" ></Script>
  <Script src="../assets/js/main.min.js" ></Script>
        {children}
     
      </body>
    
 
    </html>
  )
}
